name: "rust-ci"
description: "build x86_64, aarch64 linux rust binary fast"
inputs:
    package:
        description: "The list of packages to build(separated with ,)"
        required: true
    install-rustup:
        description: "Will install rustup for you"
        required: false
        type: boolean
        default: true
    install-openssl:
        description: "Will install openssl for aarch64 for you"
        required: false
        type: boolean
        default: false
    cache:
        description: "Cache rust for you"
        required: false
        type: boolean
        default: true
runs:
    using: "node20"
    main: dist/index.js
outputs:
    file:
        description: "Saved path"